# hash:sha256:0ee81c6e61969f24392bd2c2c40b94b2d877fffd83561e585b950c995c850a4e
FROM registry.codeocean.fresnelbio.com/codeocean/mambaforge3:22.11.1-4-ubuntu22.04

ARG DEBIAN_FRONTEND=noninteractive

ARG GIT_ASKPASS
ARG GIT_ACCESS_TOKEN
COPY git-askpass /
